version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - aaikyam_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 'aaikyam032524'
    ports:
      - "3045:3045"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - aaikyam_network
    depends_on:
      - prometheus

networks:
  aaikyam_network:
    external: true  
    
volumes:
  prometheus_data:
  grafana_data:
