version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - aaikyam_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=aaikyam032524
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    ports:
      - "3000:3000"  # Changed to standard Grafana port
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - aaikyam_network
    user: root  # Add this to resolve potential permission issues
    depends_on:
      - prometheus
    restart: unless-stopped  # Add restart policy

networks:
  aaikyam_network:
    external: true  
    
volumes:
  prometheus_data:
  grafana_data: