version: '3.9'

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 256M
      placement:
        constraints:
          - node.role == manager
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 256M
      placement:
        constraints:
          - node.role == worker
    networks:
      - monitoring

networks:
  monitoring:
    driver: overlay

volumes:
  prometheus_data:
  grafana_data:
