global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'docker'
    static_configs:
      - targets:
          - "service1:8080" # Replace with service endpoint
          - "service2:9090" # Replace with service endpoint
