global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Monitor Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['aaikyam_monitoring_service_prometheus:9090']

  # Monitor Node Exporter (host machine metrics)
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['aaikyam_node_exporter:9100']

  - job_name: 'docker_services'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: services
    relabel_configs:
      - source_labels: [__meta_dockerswarm_service_label_prometheus_scrape]
        regex: "true"
        action: keep
      - source_labels: [__meta_dockerswarm_service_label_prometheus_path]
        regex: (.+)
        target_label: __metrics_path__
      - source_labels: [__meta_dockerswarm_service_label_prometheus_port]
        regex: (.+)
        target_label: __address__
        replacement: $1

  # Services monitoring
  - job_name: 'aaikyam-frontend-dev'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['aaikyam-frontend-dev:3003']

  - job_name: 'nginx'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['195.35.7.212:9113']
  