global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alerting rules (optional, but recommended)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # Uncomment and configure if using Alertmanager
          # - alertmanager:9093

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Docker Swarm services monitoring
  - job_name: 'docker-services'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: service

  # Node exporter (for host machine metrics)
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']

  # Specific service monitoring configurations
  - job_name: 'frontend-dev'
    static_configs:
      - targets: ['localhost:3003']

  - job_name: 'admin-portal'
    static_configs:
      - targets: ['localhost:3001']

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['localhost:9200']

  - job_name: 'kibana'
    static_configs:
      - targets: ['localhost:5601']

  - job_name: 'backend-prod'
    static_configs:
      - targets: ['localhost:4000']

  - job_name: 'backend-uat'
    static_configs:
      - targets: ['localhost:4040']

  # Additional monitoring configurations
  # Add more specific job configurations as needed