global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Monitor Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['aaikyam_monitoring_service_prometheus:9090']

  # Monitor Node Exporter (host machine metrics)
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['aaikyam_node_exporter:9100']

  # Monitor Docker Swarm services
  - job_name: 'docker_services'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: services

  # Services monitoring
  - job_name: 'aaikyam-frontend-dev'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['aaikyam-frontend-dev:3003']

  