global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Monitor Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['aaikyam_monitoring_service_prometheus:9090']

  # Monitor Node Exporter (host machine metrics)
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['aaikyam_node_exporter:9100']

  # Monitor Docker Swarm services
  - job_name: 'docker_services'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: services

  # Services monitoring
  - job_name: 'aaikyam-frontend-dev'
    static_configs:
      - targets: ['aaikyam-frontend-dev:3003']

  - job_name: 'admin-portal'
    static_configs:
      - targets: ['aaikyam_admin_admin-portal:3001']

  - job_name: 'recommendation-scheduler'
    static_configs:
      - targets: ['aaikyam_ai_scheduler_recommendation_scheduler:<REPLACE_WITH_PORT>']

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['aaikyam_elk_elasticsearch:9200']

  - job_name: 'kibana'
    static_configs:
      - targets: ['aaikyam_elk_kibana:5601']

  - job_name: 'logstash'
    static_configs:
      - targets: ['aaikyam_elk_logstash:5044', 'aaikyam_elk_logstash:9600']

  - job_name: 'labs-portal'
    static_configs:
      - targets: ['aaikyam_labs_labs-portal:3002']

  - job_name: 'links-service'
    static_configs:
      - targets: ['aaikyam_links_links:5000']

  - job_name: 'mailer-service'
    static_configs:
      - targets: ['aaikyam_mailer_mailer-service:4001']

  - job_name: 'grafana'
    static_configs:
      - targets: ['aaikyam_monitoring_service_grafana:3000']

  - job_name: 'kafka'
    static_configs:
      - targets: ['aaikyam_queue_kafka:9092']

  - job_name: 'kafka-ui'
    static_configs:
      - targets: ['aaikyam_queue_kafka-ui:8001']

  - job_name: 'redis'
    static_configs:
      - targets: ['aaikyam_queue_redis:6379']

  - job_name: 'zookeeper'
    static_configs:
      - targets: ['aaikyam_queue_zookeeper:2181']

  - job_name: 'blog-recommender'
    static_configs:
      - targets: ['aaikyam_recommender_blog_recommender:8000']

  - job_name: 'backend-prod'
    static_configs:
      - targets: ['aaikyam_server_aaikyam-server-prod:4000']

  - job_name: 'backend-uat'
    static_configs:
      - targets: ['aaikyam_server_uat_aaikyam-server-uat:4040']

  - job_name: 'strapi'
    static_configs:
      - targets: ['aaikyam_strapi_strapi:1337']

  - job_name: 'frontend-beta'
    static_configs:
      - targets: ['aikyam-frontend-beta_aaikyam-frontend-beta:3005']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx_server_nginx:80']
